// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "bnl-serial_v1.0-pimpl.hxx"

// ct_HIERARCHY_pimpl
//
namespace bnl_serial_v1_0 
{
	void ct_HIERARCHY_pimpl::
	pre ()
	{
	}

	void ct_HIERARCHY_pimpl::
	FRONT ()
	{
	}

	void ct_HIERARCHY_pimpl::
	ISSUE ()
	{
	}

	void ct_HIERARCHY_pimpl::
	BACK ()
	{
	}

	void ct_HIERARCHY_pimpl::
	post_ct_HIERARCHY ()
	{
	}

	// ct_FRONT_pimpl
	//

	void ct_FRONT_pimpl::
	pre ()
	{
	}

	void ct_FRONT_pimpl::
	TITLE_SECTION ()
	{
	}

	void ct_FRONT_pimpl::
	STATEMENT_SECTION ()
	{
	}

	void ct_FRONT_pimpl::
	PICTURE_SECTION ()
	{
	}

	void ct_FRONT_pimpl::
	FRONTISPIECE ()
	{
	}

	void ct_FRONT_pimpl::
	COVER_SECTION ()
	{
	}

	void ct_FRONT_pimpl::
	BASTARD_TITLE_SECTION ()
	{
	}

	void ct_FRONT_pimpl::
	TABLE_OF_CONTENTS ()
	{
	}

	void ct_FRONT_pimpl::
	REFERENCE_LIST ()
	{
	}

	void ct_FRONT_pimpl::
	LIST_OF_PUBLICATIONS ()
	{
	}

	void ct_FRONT_pimpl::
	LIST_OF_FIGURES ()
	{
	}

	void ct_FRONT_pimpl::
	INDEX ()
	{
	}

	void ct_FRONT_pimpl::
	CORRECTIONS ()
	{
	}

	void ct_FRONT_pimpl::
	BIBLIOGRAPHY ()
	{
	}

	void ct_FRONT_pimpl::
	ABBREVIATIONS ()
	{
	}

	void ct_FRONT_pimpl::
	RIDAS ()
	{
	}

	void ct_FRONT_pimpl::
	PRODUCTION_NOTE ()
	{
	}

	void ct_FRONT_pimpl::
	PREFACE ()
	{
	}

	void ct_FRONT_pimpl::
	NECROLOGY ()
	{
	}

	void ct_FRONT_pimpl::
	INTRODUCTION ()
	{
	}

	void ct_FRONT_pimpl::
	DEDICATION ()
	{
	}

	void ct_FRONT_pimpl::
	CHAPTER ()
	{
	}

	void ct_FRONT_pimpl::
	ACKNOWLEDGEMENTS ()
	{
	}

	void ct_FRONT_pimpl::
	ABSTRACT ()
	{
	}

	void ct_FRONT_pimpl::
	ADVERTISEMENT ()
	{
	}

	void ct_FRONT_pimpl::
	post_ct_FRONT ()
	{
	}

	// ct_MAIN_pimpl
	//

	void ct_MAIN_pimpl::
	pre ()
	{
	}

	void ct_MAIN_pimpl::
	TABLE_OF_CONTENTS ()
	{
	}

	void ct_MAIN_pimpl::
	REFERENCE_LIST ()
	{
	}

	void ct_MAIN_pimpl::
	LIST_OF_PUBLICATIONS ()
	{
	}

	void ct_MAIN_pimpl::
	LIST_OF_FIGURES ()
	{
	}

	void ct_MAIN_pimpl::
	LIST ()
	{
	}

	void ct_MAIN_pimpl::
	INDEX ()
	{
	}

	void ct_MAIN_pimpl::
	CORRECTIONS ()
	{
	}

	void ct_MAIN_pimpl::
	BIBLIOGRAPHY ()
	{
	}

	void ct_MAIN_pimpl::
	ABBREVIATIONS ()
	{
	}

	void ct_MAIN_pimpl::
	RIDAS ()
	{
	}

	void ct_MAIN_pimpl::
	PRODUCTION_NOTE ()
	{
	}

	void ct_MAIN_pimpl::
	PREFACE ()
	{
	}

	void ct_MAIN_pimpl::
	POSTFACE ()
	{
	}

	void ct_MAIN_pimpl::
	POEM ()
	{
	}

	void ct_MAIN_pimpl::
	NOTES ()
	{
	}

	void ct_MAIN_pimpl::
	NECROLOGY ()
	{
	}

	void ct_MAIN_pimpl::
	INTRODUCTION ()
	{
	}

	void ct_MAIN_pimpl::
	GROUP ()
	{
	}

	void ct_MAIN_pimpl::
	DEDICATION ()
	{
	}

	void ct_MAIN_pimpl::
	DEBATE ()
	{
	}

	void ct_MAIN_pimpl::
	CONTRIBUTION ()
	{
	}

	void ct_MAIN_pimpl::
	CHAPTER ()
	{
	}

	void ct_MAIN_pimpl::
	BOOK_REVIEW ()
	{
	}

	void ct_MAIN_pimpl::
	APPENDIX ()
	{
	}

	void ct_MAIN_pimpl::
	ACKNOWLEDGEMENTS ()
	{
	}

	void ct_MAIN_pimpl::
	ABSTRACT ()
	{
	}

	void ct_MAIN_pimpl::
	ADVERTISEMENT ()
	{
	}

	void ct_MAIN_pimpl::
	post_ct_MAIN ()
	{
	}

	// ct_BACK_pimpl
	//

	void ct_BACK_pimpl::
	pre ()
	{
	}

	void ct_BACK_pimpl::
	STATEMENT_SECTION ()
	{
	}

	void ct_BACK_pimpl::
	PICTURE_SECTION ()
	{
	}

	void ct_BACK_pimpl::
	COVER_SECTION ()
	{
	}

	void ct_BACK_pimpl::
	TABLE_OF_CONTENTS ()
	{
	}

	void ct_BACK_pimpl::
	REFERENCE_LIST ()
	{
	}

	void ct_BACK_pimpl::
	LIST_OF_PUBLICATIONS ()
	{
	}

	void ct_BACK_pimpl::
	LIST_OF_FIGURES ()
	{
	}

	void ct_BACK_pimpl::
	LIST ()
	{
	}

	void ct_BACK_pimpl::
	INDEX ()
	{
	}

	void ct_BACK_pimpl::
	CORRECTIONS ()
	{
	}

	void ct_BACK_pimpl::
	BIBLIOGRAPHY ()
	{
	}

	void ct_BACK_pimpl::
	ABBREVIATIONS ()
	{
	}

	void ct_BACK_pimpl::
	RIDAS ()
	{
	}

	void ct_BACK_pimpl::
	POSTFACE ()
	{
	}

	void ct_BACK_pimpl::
	NECROLOGY ()
	{
	}

	void ct_BACK_pimpl::
	CHAPTER ()
	{
	}

	void ct_BACK_pimpl::
	APPENDIX ()
	{
	}

	void ct_BACK_pimpl::
	ACKNOWLEDGEMENTS ()
	{
	}

	void ct_BACK_pimpl::
	ADVERTISEMENT ()
	{
	}

	void ct_BACK_pimpl::
	post_ct_BACK ()
	{
	}

	// ct_ISSUE_pimpl
	//

	void ct_ISSUE_pimpl::
	pre ()
	{
	}

	void ct_ISSUE_pimpl::
	MAIN ()
	{
	}

	void ct_ISSUE_pimpl::
	FRONT ()
	{
	}

	void ct_ISSUE_pimpl::
	BACK ()
	{
	}

	void ct_ISSUE_pimpl::
	post_ct_ISSUE ()
	{
	}

	// ct_PAGE_LIKE_pimpl
	//

	void ct_PAGE_LIKE_pimpl::
	pre ()
	{
	}

	void ct_PAGE_LIKE_pimpl::
	CONTENT ()
	{
	}

	void ct_PAGE_LIKE_pimpl::
	post_ct_PAGE_LIKE ()
	{
	}

	// ct_TITLE_SECTION_pimpl
	//

	void ct_TITLE_SECTION_pimpl::
	pre ()
	{
	}

	void ct_TITLE_SECTION_pimpl::
	TITLE_OF_WORK ()
	{
	}

	void ct_TITLE_SECTION_pimpl::
	CREATOR_OF_WORK ()
	{
	}

	void ct_TITLE_SECTION_pimpl::
	PUBLISHING_STMT ()
	{
	}

	void ct_TITLE_SECTION_pimpl::
	STATEMENT ()
	{
	}

	void ct_TITLE_SECTION_pimpl::
	CONTENT ()
	{
	}

	void ct_TITLE_SECTION_pimpl::
	post_ct_TITLE_SECTION ()
	{
	}

	// ct_LIST_LIKE_pimpl
	//

	void ct_LIST_LIKE_pimpl::
	pre ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	CAPTION ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	DATA ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	TABLE_OF_CONTENTS ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	REFERENCE_LIST ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	LIST_OF_PUBLICATIONS ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	LIST_OF_FIGURES ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	LIST ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	INDEX ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	CORRECTIONS ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	BIBLIOGRAPHY ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	ABBREVIATIONS ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	ITEM ()
	{
	}

	void ct_LIST_LIKE_pimpl::
	post_ct_LIST_LIKE ()
	{
	}

	// ct_ITEM_pimpl
	//

	void ct_ITEM_pimpl::
	pre ()
	{
	}

	void ct_ITEM_pimpl::
	TEXTBLOCK ()
	{
	}

	void ct_ITEM_pimpl::
	PAGE_NUMBER ()
	{
	}

	void ct_ITEM_pimpl::
	ITEM_CAPTION ()
	{
	}

	void ct_ITEM_pimpl::
	SUBHEADLINE ()
	{
	}

	void ct_ITEM_pimpl::
	HEADLINE ()
	{
	}

	void ct_ITEM_pimpl::
	AUTHOR ()
	{
	}

	void ct_ITEM_pimpl::
	ITEM ()
	{
	}

	void ct_ITEM_pimpl::
	post_ct_ITEM ()
	{
	}

	// ct_HEADING_pimpl
	//

	void ct_HEADING_pimpl::
	pre ()
	{
	}

	void ct_HEADING_pimpl::
	TITLE ()
	{
	}

	void ct_HEADING_pimpl::
	SUBTITLE ()
	{
	}

	void ct_HEADING_pimpl::
	AUTHOR ()
	{
	}

	void ct_HEADING_pimpl::
	MOTTO ()
	{
	}

	void ct_HEADING_pimpl::
	HEADING_TEXT ()
	{
	}

	void ct_HEADING_pimpl::
	post_ct_HEADING ()
	{
	}

	// ct_CHAPTER_LIKE_pimpl
	//

	void ct_CHAPTER_LIKE_pimpl::
	pre ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	HEADING ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	ABSTRACT ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	BODY ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	TABLE_OF_CONTENTS ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	REFERENCE_LIST ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	LIST_OF_PUBLICATIONS ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	LIST_OF_FIGURES ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	INDEX ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	CORRECTIONS ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	BIBLIOGRAPHY ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	ABBREVIATIONS ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	RIDAS ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	PRODUCTION_NOTE ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	PREFACE ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	POSTFACE ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	POEM ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	NOTES ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	NECROLOGY ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	INTRODUCTION ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	GROUP ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	DEDICATION ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	DEBATE ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	CONTRIBUTION ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	CHAPTER ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	BOOK_REVIEW ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	APPENDIX ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	ACKNOWLEDGEMENTS ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	MAP_GROUP ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	ILLUSTRATION_GROUP ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	CHART_DIAGRAM_GROUP ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	TABLE_GROUP ()
	{
	}

	void ct_CHAPTER_LIKE_pimpl::
	post_ct_CHAPTER_LIKE ()
	{
	}

	// ct_MAP_GROUP_pimpl
	//

	void ct_MAP_GROUP_pimpl::
	pre ()
	{
	}

	void ct_MAP_GROUP_pimpl::
	MAP ()
	{
	}

	void ct_MAP_GROUP_pimpl::
	post_ct_MAP_GROUP ()
	{
	}

	// ct_ILLUSTRATION_GROUP_pimpl
	//

	void ct_ILLUSTRATION_GROUP_pimpl::
	pre ()
	{
	}

	void ct_ILLUSTRATION_GROUP_pimpl::
	ILLUSTRATION ()
	{
	}

	void ct_ILLUSTRATION_GROUP_pimpl::
	post_ct_ILLUSTRATION_GROUP ()
	{
	}

	// ct_CHART_DIAGRAM_GROUP_pimpl
	//

	void ct_CHART_DIAGRAM_GROUP_pimpl::
	pre ()
	{
	}

	void ct_CHART_DIAGRAM_GROUP_pimpl::
	CHART_DIAGRAM ()
	{
	}

	void ct_CHART_DIAGRAM_GROUP_pimpl::
	post_ct_CHART_DIAGRAM_GROUP ()
	{
	}

	// ct_TABLE_GROUP_pimpl
	//

	void ct_TABLE_GROUP_pimpl::
	pre ()
	{
	}

	void ct_TABLE_GROUP_pimpl::
	TABLE ()
	{
	}

	void ct_TABLE_GROUP_pimpl::
	post_ct_TABLE_GROUP ()
	{
	}

	// ct_ILLUSTRATION_LIKE_STRUCT_pimpl
	//

	void ct_ILLUSTRATION_LIKE_STRUCT_pimpl::
	pre ()
	{
	}

	void ct_ILLUSTRATION_LIKE_STRUCT_pimpl::
	IMAGE ()
	{
	}

	void ct_ILLUSTRATION_LIKE_STRUCT_pimpl::
	CAPTION ()
	{
	}

	void ct_ILLUSTRATION_LIKE_STRUCT_pimpl::
	post_ct_ILLUSTRATION_LIKE_STRUCT ()
	{
	}

	// ct_TABLE_LIKE_STRUCT_pimpl
	//

	void ct_TABLE_LIKE_STRUCT_pimpl::
	pre ()
	{
	}

	void ct_TABLE_LIKE_STRUCT_pimpl::
	IMAGE ()
	{
	}

	void ct_TABLE_LIKE_STRUCT_pimpl::
	CAPTION ()
	{
	}

	void ct_TABLE_LIKE_STRUCT_pimpl::
	post_ct_TABLE_LIKE_STRUCT ()
	{
	}

	// ct_BODY_pimpl
	//

	void ct_BODY_pimpl::
	pre ()
	{
	}

	void ct_BODY_pimpl::
	BODY_CONTENT ()
	{
	}

	void ct_BODY_pimpl::
	FOOTNOTE ()
	{
	}

	void ct_BODY_pimpl::
	MAP ()
	{
	}

	void ct_BODY_pimpl::
	ILLUSTRATION ()
	{
	}

	void ct_BODY_pimpl::
	CHART_DIAGRAM ()
	{
	}

	void ct_BODY_pimpl::
	BOOKPLATE ()
	{
	}

	void ct_BODY_pimpl::
	BARCODE ()
	{
	}

	void ct_BODY_pimpl::
	TABLE ()
	{
	}

	void ct_BODY_pimpl::
	LIST ()
	{
	}

	void ct_BODY_pimpl::
	post_ct_BODY ()
	{
	}

	// ct_BODY_CONTENT_pimpl
	//

	void ct_BODY_CONTENT_pimpl::
	pre ()
	{
	}

	void ct_BODY_CONTENT_pimpl::
	TEXTBLOCK ()
	{
	}

	void ct_BODY_CONTENT_pimpl::
	PARAGRAPH ()
	{
	}

	void ct_BODY_CONTENT_pimpl::
	FORMULA ()
	{
	}

	void ct_BODY_CONTENT_pimpl::
	post_ct_BODY_CONTENT ()
	{
	}

	// ct_FORMULA_pimpl
	//

	void ct_FORMULA_pimpl::
	pre ()
	{
	}

	void ct_FORMULA_pimpl::
	IMAGE ()
	{
	}

	void ct_FORMULA_pimpl::
	post_ct_FORMULA ()
	{
	}

	// ct_PARAGRAPH_pimpl
	//

	void ct_PARAGRAPH_pimpl::
	pre ()
	{
	}

	void ct_PARAGRAPH_pimpl::
	TEXT ()
	{
	}

	void ct_PARAGRAPH_pimpl::
	MARGINALIA ()
	{
	}

	void ct_PARAGRAPH_pimpl::
	post_ct_PARAGRAPH ()
	{
	}

	// ct_FOOTNOTE_PARAGRAPH_pimpl
	//

	void ct_FOOTNOTE_PARAGRAPH_pimpl::
	pre ()
	{
	}

	void ct_FOOTNOTE_PARAGRAPH_pimpl::
	TEXT ()
	{
	}

	void ct_FOOTNOTE_PARAGRAPH_pimpl::
	post_ct_FOOTNOTE_PARAGRAPH ()
	{
	}

	// ct_FINAL_pimpl
	//

	void ct_FINAL_pimpl::
	pre ()
	{
	}

	void ct_FINAL_pimpl::
	fptr ()
	{
	}

	void ct_FINAL_pimpl::
	post_ct_FINAL ()
	{
	}

	// ct_FPTR_pimpl
	//

	void ct_FPTR_pimpl::
	pre ()
	{
	}

	void ct_FPTR_pimpl::
	area ()
	{
	}

	void ct_FPTR_pimpl::
	seq ()
	{
	}

	void ct_FPTR_pimpl::
	par ()
	{
	}

	void ct_FPTR_pimpl::
	post_ct_FPTR ()
	{
	}

	// ct_SEQ_pimpl
	//

	void ct_SEQ_pimpl::
	pre ()
	{
	}

	void ct_SEQ_pimpl::
	area ()
	{
	}

	void ct_SEQ_pimpl::
	post_ct_SEQ ()
	{
	}

	// Serial_pimpl
	//

	void Serial_pimpl::
	pre ()
	{
	}

	void Serial_pimpl::
	VOLUME ()
	{
	}

	void Serial_pimpl::
	post_Serial ()
	{
	}

	// CONTENT_pimpl
	//

	void CONTENT_pimpl::
	pre ()
	{
	}

	void CONTENT_pimpl::
	TEXTBLOCK ()
	{
	}

	void CONTENT_pimpl::
	TABLE ()
	{
	}

	void CONTENT_pimpl::
	PUBLISHING_STMT ()
	{
	}

	void CONTENT_pimpl::
	PARAGRAPH ()
	{
	}

	void CONTENT_pimpl::
	MAP ()
	{
	}

	void CONTENT_pimpl::
	ILLUSTRATION ()
	{
	}

	void CONTENT_pimpl::
	CHART_DIAGRAM ()
	{
	}

	void CONTENT_pimpl::
	BOOKPLATE ()
	{
	}

	void CONTENT_pimpl::
	BARCODE ()
	{
	}

	void CONTENT_pimpl::
	SUBHEADLINE ()
	{
	}

	void CONTENT_pimpl::
	HEADLINE ()
	{
	}

	void CONTENT_pimpl::
	FORMULA ()
	{
	}

	void CONTENT_pimpl::
	FOOTNOTE ()
	{
	}

	void CONTENT_pimpl::
	AUTHOR ()
	{
	}

	void CONTENT_pimpl::
	post_CONTENT ()
	{
	}

	// CONTENT1_pimpl
	//

	void CONTENT1_pimpl::
	pre ()
	{
	}

	void CONTENT1_pimpl::
	TABLE ()
	{
	}

	void CONTENT1_pimpl::
	MAP ()
	{
	}

	void CONTENT1_pimpl::
	ILLUSTRATION ()
	{
	}

	void CONTENT1_pimpl::
	CHART_DIAGRAM ()
	{
	}

	void CONTENT1_pimpl::
	BOOKPLATE ()
	{
	}

	void CONTENT1_pimpl::
	BARCODE ()
	{
	}

	void CONTENT1_pimpl::
	FORMULA ()
	{
	}

	void CONTENT1_pimpl::
	post_CONTENT1 ()
	{
	}

	// DATA_pimpl
	//

	void DATA_pimpl::
	pre ()
	{
	}

	void DATA_pimpl::
	TEXTBLOCK ()
	{
	}

	void DATA_pimpl::
	PAGE_NUMBER ()
	{
	}

	void DATA_pimpl::
	ITEM_CAPTION ()
	{
	}

	void DATA_pimpl::
	AUTHOR ()
	{
	}

	void DATA_pimpl::
	post_DATA ()
	{
	}

	// MOTTO_pimpl
	//

	void MOTTO_pimpl::
	pre ()
	{
	}

	void MOTTO_pimpl::
	TEXT ()
	{
	}

	void MOTTO_pimpl::
	post_MOTTO ()
	{
	}

	// HEADING_TEXT_pimpl
	//

	void HEADING_TEXT_pimpl::
	pre ()
	{
	}

	void HEADING_TEXT_pimpl::
	TEXT ()
	{
	}

	void HEADING_TEXT_pimpl::
	post_HEADING_TEXT ()
	{
	}

	// par_pimpl
	//

	void par_pimpl::
	pre ()
	{
	}

	void par_pimpl::
	area ()
	{
	}

	void par_pimpl::
	seq ()
	{
	}

	void par_pimpl::
	post_par ()
	{
	}

}