// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX_________DATA_SCHEMAS_DC_PIMPL_HXX
#define CXX_________DATA_SCHEMAS_DC_PIMPL_HXX

#include "dc-pskel.hxx"

#include "xml-pimpl.hxx"

namespace dc
{
  class elementType_pimpl: public virtual elementType_pskel,
    public ::xml_schema::string_pimpl
  {
    public:
    virtual void
    pre ();

    virtual void
    lang (const ::std::string&);

    virtual void
    post_elementType ();
  };
}

#endif // CXX_________DATA_SCHEMAS_DC_PIMPL_HXX
