// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "dc-pimpl.hxx"

namespace dc
{
  // elementType_pimpl
  //

  void elementType_pimpl::
  pre ()
  {
  }

  void elementType_pimpl::
  lang (const ::std::string& lang)
  {
    // TODO
    //
  }

  void elementType_pimpl::
  post_elementType ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
  }
}

