// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX_________DATA_SCHEMAS_RDF_PIMPL_HXX
#define CXX_________DATA_SCHEMAS_RDF_PIMPL_HXX

#include "rdf-pskel.hxx"

#include "dc-pimpl.hxx"

namespace rdf
{
  class RDF_pimpl: public virtual RDF_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    Description ();

    virtual void
    post_RDF ();
  };

  class Description_pimpl: public virtual Description_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    post_Description ();
  };
}

#endif // CXX_________DATA_SCHEMAS_RDF_PIMPL_HXX
