// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "rdf-pimpl.hxx"

namespace rdf
{
  // RDF_pimpl
  //

  void RDF_pimpl::
  pre ()
  {
  }

  void RDF_pimpl::
  Description ()
  {
  }

  void RDF_pimpl::
  post_RDF ()
  {
  }

  // Description_pimpl
  //

  void Description_pimpl::
  pre ()
  {
  }

  void Description_pimpl::
  post_Description ()
  {
  }
}

