// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "xlink-pimpl.hxx"

namespace xlink
{
  // show_pimpl
  //

  void show_pimpl::
  pre ()
  {
  }

  void show_pimpl::
  post_show ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
  }

  // actuate_pimpl
  //

  void actuate_pimpl::
  pre ()
  {
  }

  void actuate_pimpl::
  post_actuate ()
  {
    const ::std::string& v (post_string ());

    // TODO
    //
  }
}

