// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "xml-pimpl.hxx"

namespace namespace_
{
  // space_pimpl
  //

  void space_pimpl::
  pre ()
  {
  }

  void space_pimpl::
  post_space ()
  {
    const ::std::string& v (post_ncname ());

    // TODO
    //
  }
}

