// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX_________DATA_SCHEMAS_XML_PIMPL_HXX
#define CXX_________DATA_SCHEMAS_XML_PIMPL_HXX

#include "xml-pskel.hxx"

namespace namespace_
{
  class space_pimpl: public virtual space_pskel,
    public ::xml_schema::ncname_pimpl
  {
    public:
    virtual void
    pre ();

    virtual void
    post_space ();
  };
}

#endif // CXX_________DATA_SCHEMAS_XML_PIMPL_HXX
